# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            AttitudeAnalytiks
tagline:          Senior Project
url:              AttitudeAnalytiks.github.io
paginate:         1
baseurl:          /
author:
  name:           Kelly O'Conor
  url:            koconor.github.io
  email:          koconor@villanova.edu

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/AttitudeAnalytiks/AttitudeAnalytiks.github.io

#page lists
pages_list:       
  About: '/about'
  CSC 4790: 'csc.villanova.edu/~joyce/csc4790/f14/index.html'
  Archive: '/archive'
  Feed: '/atom.xml'
  
